# practice list
bicycles  = ['trek', 'cannondale', 'redline', 'specialized']
print bicycles[0]
print bicycles[-1]
bicycles[0] = 'ofo'

bicycles.append('mobi')

# add element to the end of the list
auto_cars = []
auto_cars.append('honda')
auto_cars.append('toyota')

print auto_cars

# add an element at some specific position.
auto_cars.insert(1, 'mazda')
print len(auto_cars)

# remove element, del
del auto_cars[0]
print len(auto_cars)

# remove last element and use that
last_element = auto_cars.pop()
print 'Last element is : ' + last_element + '.'

auto_cars = ['honda', 'toyota', 'mazda']
# use pop to remove element at any position
prev_element = auto_cars.pop(1)
print auto_cars

# remove an element from list
auto_cars.remove('honda')
print auto_cars

# Execise 3-4
guests = ['Le Yang', 'Melody Zhou', 'Jianwei Tu', 'Jingwen Yi', 'Di Wang', 'Yurui Xiao']
for g in guests:
    print 'Welcome to my house, ' + g + '!'

# Execise 3-5
guests.insert(0, 'Junfei Ren')
guests.insert(2, 'Lei Huang')
guests.append('Xiayu Hua')

# sort (permanently)
auto_cars = ['bmw', 'audi', 'toyota', 'subaru']
print 'Before sorting, the list is ' + str(auto_cars)
auto_cars.sort()
print 'After sorting, the list is ' + str(auto_cars)

# reverse sort
auto_cars.sort(reverse=True)

# sort (temporarily)
sorted(auto_cars)

# reverse a list
auto_cars.reverse()

# find the len of a list
print 'There are ' + str(len(auto_cars)) + ' kinds of cars.\n\n'

# iterate a list
magicians = ['alice', 'david', 'carolina']
for magician in magicians:
    print magician

# use a range
for i in range(1, 5):
    # 1, 2, 3, 4
    print 'Number ' + str(i) + ' is generated by \'range\' function.'

# convert a range to a list
nums = list(range(1, 11))
print nums

# statistics with a list of numberss
print 'Minimal value is ' + str(min(nums)) + '.'
print 'Maximal value is ' + str(max(nums)) + '.'
print 'Sum is ' + str(sum(nums)) + '.'

# list comprehensions
squares = [i ** 2 for i in range(1, 101)]
print sum(squares)

# slice a list
print squares[1:50]
print squares[:50]
print squares[2:]
# last three elements
print squares[-3:]
# all the elements
print squares[:]
# copying a list
new_squares = squares[:]
print sum(new_squares)

# tuple is an immutable list
dimensions = (200, 50)

